
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stleylfmcokqartpldpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0bGV5bGZtY29rcWFydHBsZHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODc5NjIsImV4cCI6MjA2Mjk2Mzk2Mn0.ioRB9iio9VqMxFNNUlq3bldGLB9X_kSVNsh6H-BBDyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  }
});
